org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Keystore configuration for App Links (same keystore for debug and release)
KEYSTORE_STORE_PASSWORD=***REMOVED***
KEYSTORE_KEY_PASSWORD=***REMOVED***
KEYSTORE_ALIAS=my_key
