// lib/domain/entities/organizacion.dart

import 'package:equatable/equatable.dart';

import 'enums.dart';

/// Entidad de dominio para Organización (grupos/colectivos de emprendedores)
/// Basado en la tabla real de la base de datos:
/// CREATE TABLE public.organizacion (
///   id bigint generated by default as identity not null,
///   created_at timestamp with time zone not null default now(),
///   anfitrion_id bigint not null,
///   nombre character varying null,
///   descripcion text null,
///   email_anfitrion character varying not null,
///   tipo public.tipo_organizacion not null,
///   constraint organizacion_pkey primary key (id)
/// ) TABLESPACE pg_default;
class Organizacion extends Equatable {
  final int id;
  final DateTime createdAt;
  final int anfitrionId; // FK a usuario (anfitrión)
  final String? nombre;
  final String? descripcion;
  final String emailAnfitrion;
  final TipoOrganizacion tipo;

  // Campos calculados/derivados (no en DB)
  final String? logoUrl;
  final List<Map<String, dynamic>>? imagenes;
  final int? totalMiembros;
  final int? totalTiendas;
  final int? totalVisitas;
  final Map<String, dynamic>? metadata;

  const Organizacion({
    required this.id,
    required this.createdAt,
    required this.anfitrionId,
    this.nombre,
    this.descripcion,
    required this.emailAnfitrion,
    required this.tipo,
    // Campos derivados
    this.logoUrl,
    this.imagenes,
    this.totalMiembros,
    this.totalTiendas,
    this.totalVisitas,
    this.metadata,
  });

  /// Factory method para crear desde JSON (Supabase)
  factory Organizacion.fromJson(Map<String, dynamic> json) {
    return Organizacion(
      id: json['id'] as int,
      createdAt: DateTime.parse(json['created_at'] as String),
      anfitrionId: json['anfitrion_id'] as int,
      nombre: json['nombre'] as String?,
      descripcion: json['descripcion'] as String?,
      emailAnfitrion: json['email_anfitrion'] as String,
      tipo: TipoOrganizacion.fromString(json['tipo'] as String),
      // Campos derivados (pueden venir de joins o cálculos)
      logoUrl: json['logo_url'] as String?,
      imagenes: _parseImagenesOrganizacion(json),
      totalMiembros: _parseContadorMiembros(json),
      totalTiendas: _parseContadorTiendas(json),
      totalVisitas: json['total_visitas'] as int?,
      metadata: json['metadata'] as Map<String, dynamic>?,
    );
  }

  /// Convertir a JSON para Supabase
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'created_at': createdAt.toIso8601String(),
      'anfitrion_id': anfitrionId,
      'nombre': nombre,
      'descripcion': descripcion,
      'email_anfitrion': emailAnfitrion,
      'tipo': tipo.value,
      // Campos derivados (solo para cache/local)
      if (logoUrl != null) 'logo_url': logoUrl,
      if (totalMiembros != null) 'total_miembros': totalMiembros,
      if (totalTiendas != null) 'total_tiendas': totalTiendas,
      if (totalVisitas != null) 'total_visitas': totalVisitas,
      if (metadata != null) 'metadata': metadata,
    };
  }

  /// Verificar si la organización tiene nombre
  bool get tieneNombre => nombre != null && nombre!.isNotEmpty;

  /// Verificar si tiene descripción
  bool get tieneDescripcion => descripcion != null && descripcion!.isNotEmpty;

  /// Obtener nombre para mostrar (usa nombre o email como fallback)
  String get nombreParaMostrar {
    if (tieneNombre) return nombre!;
    return 'Organización ${id.toString()}';
  }

  /// Verificar si es del tipo fundación
  bool get esFundacion => tipo == TipoOrganizacion.fundacion;

  /// Verificar si es del tipo asociación
  bool get esAsociacion => tipo == TipoOrganizacion.asociacion;

  /// Verificar si es del tipo cooperativa
  bool get esCooperativa => tipo == TipoOrganizacion.cooperativa;

  /// Verificar si es del tipo empresa
  bool get esEmpresa => tipo == TipoOrganizacion.empresa;

  /// Verificar si es del tipo comunidad
  bool get esComunidad => tipo == TipoOrganizacion.comunidad;

  /// Obtener icono según tipo
  String get iconoTipo {
    switch (tipo) {
      case TipoOrganizacion.fundacion:
        return '🏛️';
      case TipoOrganizacion.asociacion:
        return '🤝';
      case TipoOrganizacion.cooperativa:
        return '👥';
      case TipoOrganizacion.empresa:
        return '🏢';
      case TipoOrganizacion.comunidad:
        return '🏘️';
      case TipoOrganizacion.otro:
        return '🏠';
    }
  }

  /// Obtener color según tipo
  String get colorTipo {
    switch (tipo) {
      case TipoOrganizacion.fundacion:
        return '#9C27B0'; // Púrpura
      case TipoOrganizacion.asociacion:
        return '#2196F3'; // Azul
      case TipoOrganizacion.cooperativa:
        return '#4CAF50'; // Verde
      case TipoOrganizacion.empresa:
        return '#FF9800'; // Naranja
      case TipoOrganizacion.comunidad:
        return '#F44336'; // Rojo
      case TipoOrganizacion.otro:
        return '#607D8B'; // Gris azulado
    }
  }

  /// Obtener descripción del tipo
  String get descripcionTipo {
    switch (tipo) {
      case TipoOrganizacion.fundacion:
        return 'Fundación';
      case TipoOrganizacion.asociacion:
        return 'Asociación';
      case TipoOrganizacion.cooperativa:
        return 'Cooperativa';
      case TipoOrganizacion.empresa:
        return 'Empresa';
      case TipoOrganizacion.comunidad:
        return 'Comunidad';
      case TipoOrganizacion.otro:
        return 'Otra Organización';
    }
  }

  /// Verificar si es una organización activa (basado en lógica de negocio)
  bool get estaActiva {
    // Una organización se considera activa si tiene tiendas o miembros
    return (totalTiendas ?? 0) > 0 || (totalMiembros ?? 0) > 0;
  }

  /// Verificar si es una organización popular
  bool get esPopular => (totalVisitas ?? 0) > 100;

  /// Obtener nivel de actividad
  String get nivelActividad {
    final tiendas = totalTiendas ?? 0;
    final miembros = totalMiembros ?? 0;

    if (tiendas > 10 || miembros > 50) return 'Alta';
    if (tiendas > 3 || miembros > 10) return 'Media';
    return 'Baja';
  }

  /// Copiar con nuevos valores
  Organizacion copyWith({
    int? id,
    DateTime? createdAt,
    int? anfitrionId,
    String? nombre,
    String? descripcion,
    String? emailAnfitrion,
    TipoOrganizacion? tipo,
    String? logoUrl,
    List<Map<String, dynamic>>? imagenes,
    int? totalMiembros,
    int? totalTiendas,
    int? totalVisitas,
    Map<String, dynamic>? metadata,
  }) {
    return Organizacion(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      anfitrionId: anfitrionId ?? this.anfitrionId,
      nombre: nombre ?? this.nombre,
      descripcion: descripcion ?? this.descripcion,
      emailAnfitrion: emailAnfitrion ?? this.emailAnfitrion,
      tipo: tipo ?? this.tipo,
      logoUrl: logoUrl ?? this.logoUrl,
      imagenes: imagenes ?? this.imagenes,
      totalMiembros: totalMiembros ?? this.totalMiembros,
      totalTiendas: totalTiendas ?? this.totalTiendas,
      totalVisitas: totalVisitas ?? this.totalVisitas,
      metadata: metadata ?? this.metadata,
    );
  }

  /// Copiar con campos derivados actualizados
  Organizacion copyWithDerivados({
    String? logoUrl,
    int? totalMiembros,
    int? totalTiendas,
    int? totalVisitas,
    Map<String, dynamic>? metadata,
  }) {
    return copyWith(
      logoUrl: logoUrl,
      totalMiembros: totalMiembros,
      totalTiendas: totalTiendas,
      totalVisitas: totalVisitas,
      metadata: metadata,
    );
  }

  @override
  List<Object?> get props => [
    id,
    createdAt,
    anfitrionId,
    nombre,
    descripcion,
    emailAnfitrion,
    tipo,
    logoUrl,
    imagenes,
    totalMiembros,
    totalTiendas,
    totalVisitas,
    metadata,
  ];

  @override
  bool get stringify => true;

  /// Métodos de utilidad para UI
  String get resumenInfo {
    final partes = <String>[];
    if (totalTiendas != null && totalTiendas! > 0) {
      partes.add('$totalTiendas tienda${totalTiendas! > 1 ? 's' : ''}');
    }
    if (totalMiembros != null && totalMiembros! > 0) {
      partes.add('$totalMiembros miembro${totalMiembros! > 1 ? 's' : ''}');
    }
    if (partes.isEmpty) return 'Nueva organización';
    return partes.join(' • ');
  }

  /// Verificar si necesita actualización (información muy antigua)
  bool necesitaActualizacion() {
    final seisMesesAtras = DateTime.now().subtract(const Duration(days: 180));
    return createdAt.isBefore(seisMesesAtras);
  }

  /// Obtener tiempo desde creación
  String get tiempoDesdeCreacion {
    final ahora = DateTime.now();
    final diferencia = ahora.difference(createdAt);

    if (diferencia.inDays > 365) {
      final anos = (diferencia.inDays / 365).floor();
      return '$anos año${anos > 1 ? 's' : ''}';
    } else if (diferencia.inDays > 30) {
      final meses = (diferencia.inDays / 30).floor();
      return '$meses mes${meses > 1 ? 'es' : ''}';
    } else if (diferencia.inDays > 0) {
      return '${diferencia.inDays} día${diferencia.inDays > 1 ? 's' : ''}';
    } else if (diferencia.inHours > 0) {
      return '${diferencia.inHours} hora${diferencia.inHours > 1 ? 's' : ''}';
    } else {
      return 'Hace unos minutos';
    }
  }

  /// Método para ordenar organizaciones
  static int compararPorActividad(Organizacion a, Organizacion b) {
    // Primero por número de tiendas
    final tiendasA = a.totalTiendas ?? 0;
    final tiendasB = b.totalTiendas ?? 0;
    if (tiendasA != tiendasB) return tiendasB.compareTo(tiendasA);

    // Luego por número de miembros
    final miembrosA = a.totalMiembros ?? 0;
    final miembrosB = b.totalMiembros ?? 0;
    if (miembrosA != miembrosB) return miembrosB.compareTo(miembrosA);

    // Finalmente por fecha de creación (más reciente primero)
    return b.createdAt.compareTo(a.createdAt);
  }

  /// Obtener la URL del logo principal (primera imagen de tipo 'logo')
  String? get logoUrlPrincipal {
    if (imagenes != null && imagenes!.isNotEmpty) {
      // Buscar imagen de tipo 'logo'
      final logoImage = imagenes!.firstWhere(
        (img) => img['tipo_imagen'] == 'logo',
        orElse: () => imagenes!.first,
      );
      return logoImage['url_imagen'] as String?;
    }
    return logoUrl;
  }

  /// Obtener todas las imágenes de galería
  List<Map<String, dynamic>> get imagenesGaleria {
    if (imagenes == null) return [];
    return imagenes!.where((img) => img['tipo_imagen'] != 'logo').toList();
  }

  /// Método auxiliar para parsear imágenes de organización
  static List<Map<String, dynamic>>? _parseImagenesOrganizacion(
    Map<String, dynamic> json,
  ) {
    final imagenesData = json['imagen_organizacion'];
    if (imagenesData == null) return null;

    if (imagenesData is List) {
      return List<Map<String, dynamic>>.from(imagenesData);
    } else if (imagenesData is Map<String, dynamic>) {
      return [imagenesData];
    }
    return null;
  }

  /// Método auxiliar para parsear contador de tiendas
  static int? _parseContadorTiendas(Map<String, dynamic> json) {
    final tiendasData = json['tiendas'];
    if (tiendasData == null) return null;

    if (tiendasData is List) {
      return tiendasData.length;
    } else if (tiendasData is Map<String, dynamic>) {
      // Si viene como objeto con count
      if (tiendasData.containsKey('count')) {
        return tiendasData['count'] as int?;
      }
      return 1; // Si es un objeto individual, hay al menos 1
    }
    return 0;
  }

  /// Método auxiliar para parsear contador de miembros
  static int? _parseContadorMiembros(Map<String, dynamic> json) {
    final miembrosData = json['miembros'];
    if (miembrosData == null) return null;

    if (miembrosData is List) {
      return miembrosData.length;
    } else if (miembrosData is Map<String, dynamic>) {
      // Si viene como objeto con count
      if (miembrosData.containsKey('count')) {
        return miembrosData['count'] as int?;
      }
      return 1; // Si es un objeto individual, hay al menos 1
    }
    return 0;
  }

  /// Método para filtrar organizaciones por tipo
  static bool filtrarPorTipo(
    Organizacion organizacion,
    TipoOrganizacion? tipoFiltro,
  ) {
    if (tipoFiltro == null) return true;
    return organizacion.tipo == tipoFiltro;
  }

  /// Método para buscar en nombre y descripción
  static bool buscarEnContenido(Organizacion organizacion, String query) {
    if (query.isEmpty) return true;

    final queryLower = query.toLowerCase();
    final nombreLower = organizacion.nombre?.toLowerCase() ?? '';
    final descripcionLower = organizacion.descripcion?.toLowerCase() ?? '';
    final emailLower = organizacion.emailAnfitrion.toLowerCase();

    return nombreLower.contains(queryLower) ||
        descripcionLower.contains(queryLower) ||
        emailLower.contains(queryLower);
  }
}
